name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    services:
      consul:
        image: consul:1.10.3
        env:
          CONSUL_BIND_INTERFACE: eth0
        ports:
          - 8300-8302:8300-8302/tcp
          - 8301-8302:8301-8302/udp
          - 8500:8500/tcp
          - 8600:8600/tcp
          - 8600:8600/udp
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build

    - name: Test
      run: make test && make coverage
      env:
        CONSUL_ADDR: localhost:8500
        DEREGISTER_CRITICAL_SERVICE_AFTER_SECONDS: 5

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage.out